version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"     # VS debug http
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: seguridad
      POSTGRES_PASSWORD: seguridad123
      POSTGRES_DB: seguridad
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seguridad"]
      interval: 5s
      retries: 10

volumes:
  pgdata:
